# Generated by Django 3.2.8 on 2023-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patients', '0053_auto_20230315_1257'),
    ]

    def __init__(self, *args, **kwargs):
        try:
            super().__init__(*
    ]

try:
    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='field_name',
            field=models.CharField(max_length=100),
        )
    ]
except Exception as e:
    print(f"An error occurred: {e}")
            name='refreshed_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
